Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Models/ErrorViewModel.cs
using System;

namespace OnlineShopping.Client.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/ViewModels/NavigationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShopping.Client.Web.ViewModels
{
    public class NavigationsViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/ViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShopping.Client.Web.ViewModels
{
    public class RegisterViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Repassword { get; set; }
        public string Email { get; set; }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShopping.Client.Web.ViewModels
{
    public class UserViewModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
        public bool RememberMe { get; set; } = true;
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShopping.Client.Web.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShopping.Client.Web.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShopping.Client.Web.Controllers
{
    public class BaseController : Controller
    {
        public virtual ActionResult News()
        {
            return PartialView("Navigation_PartialView");
        }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShopping.Client.Web.Controllers
{
    public class CheckoutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShopping.Client.Web.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShopping.Client.Web.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index(string token)
        {
            ViewData["token"] = token;
            return View();
        }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShopping.Client.Web.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnlineShopping.API.Client.Clients;
using OnlineShopping.Client.Web.ViewModels;

namespace OnlineShopping.Client.Web.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IAccounts _accounts;

        public RegisterController(IAccounts accounts)
        {
            _accounts = accounts;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [Route("register")]
        public async Task<IActionResult> RegisterAccout(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index");
            }

            if (!string.Equals(
                model.Password.Trim(), model.Repassword.Trim(), StringComparison.OrdinalIgnoreCase))
            {
                return View("Index");
            }

            var register = await _accounts.Register(
                model.Username, model.Password, model.Email);

            if (register == null)
            {
                return View();
            }

            return RedirectToAction("Login", "User");
        }
    }

}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineShopping.API.Client.Clients;
using OnlineShopping.API.Domains.Shares;
using OnlineShopping.Client.Web.ViewModels;
using OnlineShopping.Services.Accounts;

namespace OnlineShopping.Client.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IAccounts _accounts;
        private readonly ICryptoService _cryptoService;
        public UserController(IAccounts accounts, ICryptoService cryptoService)
        {
            _accounts = accounts;
            _cryptoService = cryptoService;
        }
        [Route("/login")]
        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }
        
        [Route("/login")]
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoginAsync(string returnUrl, UserViewModel model)
        {
            var username = model.Username;
            var password = model.Password;
            if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password))
            {
                return View();
            }

            var loginResponse = await _accounts.Login(username, password);

            if (loginResponse.IsUser)
            {
                CreateAccountCookie("_tk", loginResponse.Token, 120);
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, model.Username.Trim()));

                var principle = new ClaimsPrincipal(identity);
                var properties = new AuthenticationProperties { IsPersistent = model.RememberMe };
                await HttpContext.SignInAsync(principle, properties);

                return RedirectToAction(returnUrl ?? "Index", "Home", new { token = loginResponse.Token ?? "" });
            }

            return View("Login");
        }
        private void CreateAccountCookie(string key, string value, int? expireTime)
        {
            var option = new CookieOptions();

            if (expireTime.HasValue)
            {
                option.Expires = DateTime.Now.AddMinutes(expireTime.Value);
            }
            else
                option.Expires = DateTime.Now.AddSeconds(10);
            Response.Cookies.Append(key, value, option);
        }
    }
}

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Views/About/Index.cshtml
@{
    ViewData["Title"] = "Giới thiệu";
}
<!doctype html>
<html class="no-js" lang="en">

<body class="about">
    <!-- header-area-start -->
    <!-- header-area-end -->
    <!-- breadcrumbs-area-start -->
    <div class="breadcrumbs-area mb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumbs-menu">
                        <ul>
                            <li><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                            <li><a href="#" class="active">Giới thiệu</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumbs-area-end -->
    <!-- about-main-area-start -->
    <div class="about-main-area mb-70">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
                    <div class="about-img">
                        <a href="#"><img src="img/banner/32.jpg" alt="man" /></a>
                    </div>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                    <div class="about-content">
                        <h3>Tại sao?</h3><br/>
                        <h3>Khách hàng nên lựa chọn chúng tôi?</h3>
                        <p>@*Với gần 15 năm trong lĩnh vực phân phối và bán lẻ*@</p>
                        <ul>
                            <li><a href="#"><i class="fa fa-check"></i></a></li>
                            <li><a href="#"><i class="fa fa-check"></i></a></li>
                            <li><a href="#"><i class="fa fa-check"></i></a></li>
                            <li><a href="#"><i class="fa fa-check"></i></a></li>
                            <li><a href="#"><i class="fa fa-check"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- about-main-area-end -->
    <!-- our-mission-area-start -->
    <div class="our-mission-area mb-70">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-misson">
                        <h3><span>Kinh nghiệm</span></h3>
                        <p>Huis nostrud exerci tation ullamcorper suscipites lobortis nisl ut aliquip ex ea commodo consequat. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius claritas.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-misson">
                        <h3>Sứ mệnh<span>của chúng tôi</span></h3>
                        <p>Huis nostrud exerci tation ullamcorper suscipites lobortis nisl ut aliquip ex ea commodo consequat. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius claritas.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-misson mrg-none-xs">
                        <h3>Tầm nhìn<span>của chúng tôi</span></h3>
                        <p>Puis nostrud exerci tation ullamcorper suscipito lobortis nisl ut aliquip ex ea commodo consequat. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius claritas.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- our-mission-area-end -->
    <!-- counter-area-start -->
    <div class="counter-area ptb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-counter text-center">
                        <h2 class="counter">99</h2>
                        <span>projects completed</span>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-counter text-center">
                        <h2 class="counter">180</h2>
                        <span>Happy Clients</span>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-counter text-center">
                        <h2 class="counter">500</h2>
                        <span>Cups of Coffe</span>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 hidden-sm col-xs-12">
                    <div class="single-counter text-center mrg-none-sm mrg-none-xs">
                        <h2 class="counter">320</h2>
                        <span>Awards Winner</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- counter-area-end -->
    <!-- team-area-start -->
    <div class="team-area ptb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="team-title text-center mb-50">
                        <h2>Đội ngũ của chúng tôi</h2>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-team">
                        <div class="team-img-area">
                            <div class="team-img">
                                <a href="#"><img src="img/team/1.jpg" alt="man" /></a>
                            </div>
                            <div class="team-link">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="team-content text-center">
                            <h3>Nguyễn Ngọc Thạch</h3>
                            <span>Chủ cửa hàng</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-team">
                        <div class="team-img-area">
                            <div class="team-img">
                                <a href="#"><img src="img/team/2.jpg" alt="man" /></a>
                            </div>
                            <div class="team-link">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="team-content text-center">
                            <h3>Phan Thị Thùy Trang</h3>
                            <span>Chủ cửa hàng</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-team">
                        <div class="team-img-area">
                            <div class="team-img">
                                <a href="#"><img src="img/team/3.jpg" alt="man" /></a>
                            </div>
                            <div class="team-link">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="team-content text-center">
                            <h3>Maria Alessis</h3>
                            <span>Class Master</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 hidden-sm col-xs-12">
                    <div class="single-team mrg-none-xs">
                        <div class="team-img-area">
                            <div class="team-img">
                                <a href="#"><img src="img/team/4.jpg" alt="man" /></a>
                            </div>
                            <div class="team-link">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="team-content text-center">
                            <h3>John Doe</h3>
                            <span>PHP Devloper</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- team-area-end -->
    <!-- skill-area-start -->
    
    <!-- skill-area-end -->
    <!-- footer-area-start -->


</body>
</html>

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Views/Register/Index.cshtml
@model OnlineShopping.Client.Web.ViewModels.RegisterViewModel
@{
    ViewData["Title"] = "Đăng ký tài khoản";
}

<!doctype html>
<html class="no-js" lang="en">

<body class="register">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Add your site or application content here -->
    <!-- header-area-start -->
    <!-- header-area-end -->
    <!-- breadcrumbs-area-start -->
    <div class="breadcrumbs-area mb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumbs-menu">
                        <ul>
                            <li><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                            <li><a href="#" class="active">Đăng ký tài khoản</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="card bg-light">
                <article class="card-body mx-auto">
                    <h4 class="card-title mt-3 text-center">Tạo tài khoản</h4>
                    <form>
                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                            </div>
                            <input name="" class="form-control" placeholder="Họ và tên" type="text">
                        </div> <!-- form-group// -->
                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                            </div>
                            <input name="" class="form-control" placeholder="Địa chỉ email" type="email">
                        </div> <!-- form-group// -->

                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                            </div>
                            <input class="form-control" placeholder="Nhập mật khẩu" type="password">
                        </div> <!-- form-group// -->
                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                            </div>
                            <input class="form-control" placeholder="Nhập lại mật khẩu" type="password">
                        </div> <!-- form-group// -->
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Tạo tài khoản  </button>
                        </div> <!-- form-group// -->
                        <p class="text-center">Bạn đã có tài khoản? <a href="@Url.Action("Login","User")">Đăng nhập</a> </p>
                    </form>
                </article>
            </div> <!-- card.// -->

        </div>
        <!--container end.//-->
    </div>
    <!-- breadcrumbs-area-end -->
    <!-- user-login-area-start -->
    @*<div class="user-login-area mb-70">
            <div class="container">
                <div class="row">
                    <div style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="col-lg-12">
                        <div class="login-title text-center mb-30">
                            <h2>Đăng ký</h2>
                            <form asp-action="RegisterAccout" asp-controller="Register" method="post">
                                <div class="col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12">
                                    <div class="billing-fields">

                                        <div class="single-register">
                                            <label>Tên đăng nhập</label>
                                            <input type="text" asp-for="Username" />
                                        </div>
                                        <div class="single-register">
                                            <label>Mật khẩu</label>
                                            <input type="password" asp-for="Password" />
                                        </div>
                                        <div class="single-register">
                                            <label>Nhập lại mật khẩu</label>
                                            <input type="password" asp-for="Repassword" />
                                        </div>
                                        <div class="single-register">
                                            <label>Email</label>
                                            <input type="email" asp-for="Email" />
                                        </div>
                                        <div class="single-register" style="text-align:center">
                                            <button href="@Url.Action("Login","User")" class="btn btn-secondary w-25">Hủy</button>
                                            <button class="btn btn-success w-25">Đăng ký</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>*@
    <!-- user-login-area-end -->
    <!-- footer-area-start -->

    <link rel="stylesheet" href="~/css/register.css">

</body>
</html>

Sources/Services/OnlineShopping/OnlineShopping.Client.Web/Views/Shared/Header.cshtml
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Koparion – Book Shop Bootstrap 4 Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script&display=swap&subset=latin-ext" rel="stylesheet">

</head>
<header>
   
    <div class="header-mid-area ptb-40">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-5 col-xs-12">
                    <div class="logo-area text-center logo-xs-mrg">
                        @*<a href="index.html"><img src="img/logo/logo.png" alt="logo" /></a>*@
                        <h1 href="@Url.Action("Index","Home")" class="mt-2" style="color:green;font-family: 'Microsoft Tai Le', cursive;">Thach Trang</h1>
                    </div>

                </div>
                <div class="col-lg-4 col-md-6 col-sm-4 col-xs-12">
                    <div class="header-search">
                        <form action="#">
                            <input type="text" placeholder="Tìm kiếm sản phẩm tại đây" />
                            <a href="#"><i class="fa fa-search"></i></a>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="my-cart">
                        <ul>
                            <li>
                                <a href="@Url.Action("Login","User")"><i class="fa fa-sign-in"></i>Đăng nhập/Đăng ký</a>                              
                                <div class="mini-cart-sub">
                                   
                                    <div class="cart-bottom">
                                        <a class="view-cart" href="@Url.Action("Login","User")">Đăng nhập</a>
                                        <a href="@Url.Action("Index","Register")">Đăng ký</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                   
                </div>
                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
                    <div class="my-cart">
                        <ul>
                            <li>
                                <a href="#"><i class="fa fa-shopping-cart"></i>Giỏ hàng</a>
                                <span>2</span>
                                <div class="mini-cart-sub">
                                    <div class="cart-product">
                                        <div class="single-cart">
                                            <div class="cart-img">
                                                <a href="#"><img src="img/product/1.jpg" alt="book" /></a>
                                            </div>
                                            <div class="cart-info">
                                                <h5><a href="#">Joust Duffle Bag</a></h5>
                                                <p>1 x £60.00</p>
                                            </div>
                                            <div class="cart-icon">
                                                <a href="#"><i class="fa fa-remove"></i></a>
                                            </div>
                                        </div>
                                        <div class="single-cart">
                                            <div class="cart-img">
                                                <a href="#"><img src="img/product/3.jpg" alt="book" /></a>
                                            </div>
                                            <div class="cart-info">
                                                <h5><a href="#">Chaz Kangeroo Hoodie</a></h5>
                                                <p>1 x £52.00</p>
                                            </div>
                                            <div class="cart-icon">
                                                <a href="#"><i class="fa fa-remove"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="cart-totals">
                                        <h5>Tổng tiền <span>£12.00</span></h5>
                                    </div>
                                    <div class="cart-bottom">
                                        <a class="view-cart" href="cart.html">Xem giỏ hàng</a>
                                        <a href="@Url.Action("Index","Checkout")">Thanh toán</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- header-mid-area-end -->  
</header>